# Generated by Django 4.0.1 on 2022-05-24 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.TextField(max_length=100)),
                ('username', models.TextField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=12)),
                ('nationality', models.TextField(max_length=60)),
                ('age', models.IntegerField()),
                ('password', models.TextField(max_length=100)),
                ('repassword', models.TextField(max_length=100)),
            ],
        ),
    ]
